name: isolate_json
description: Library for using a long-lived isolate for JSON encoding and decoding.
version: 2.1.0+1
homepage: https://github.com/chmoore889/isolate_json

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
